version: '2'
services:
  datamanager:
    build:
        context: ./datamanager
        dockerfile: Dockerfile-dataman
    networks:
      app_net:
        ipv4_address: 10.123.123.100

  scanner:
    build:
        context: ./scanner
        dockerfile: Dockerfile-scanner
    command: python /root/pythonfakelog.py
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler1:
    build:
        context: ./msg-handler
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py 10.18.122.23
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler2:
    build:
        context: ./msg-handler
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py 10.18.122.24
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler3:
    build:
        context: ./msg-handler
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py 10.18.122.30
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"

  rabbit1:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672"
        - "5672:5672"
    labels:
        NAME: "rabbitmq1"
    networks:
      app_net:
        ipv4_address: 10.123.123.253
        
  replica1:
    build:
        context: ./database
        dockerfile: Dockerfile
        args:
          id : 0
    networks:
      app_net:
        ipv4_address: 10.123.123.200

  replica2:
    build:
        context: ./database
        dockerfile: Dockerfile
        args:
          id : 1
    networks:
      app_net:
        ipv4_address: 10.123.123.201

  replica3:
    build:
        context: ./database
        dockerfile: Dockerfile
        args:
          id : 2
    networks:
      app_net:
        ipv4_address: 10.123.123.202

  replica4:
    build:
        context: ./database
        dockerfile: Dockerfile
        args:
          id : 3
    networks:
      app_net:
        ipv4_address: 10.123.123.203

  replica5:
    build:
        context: ./database
        dockerfile: Dockerfile
        args:
          id : 4
    networks:
      app_net:
        ipv4_address: 10.123.123.204

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.123.123.0/24       
