version: '2'
services:
  scanner:
    build:
        context: ./
        dockerfile: Dockerfile
    command: sleep 5 
    command: /root/fakelogmaker.sh
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler1:
    build:
        context: ./
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py topic1
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler2:
    build:
        context: ./
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py topic2
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler3:
    build:
        context: ./
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py topic3
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"
  msg-handler4:
    build:
        context: ./
        dockerfile: Dockerfile-msghandler
    command: python /root/receiver.py topic4
    depends_on:
        - "rabbit1"
    networks:
        - "app_net"


  rabbit1:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672"
        - "5672:5672"
    labels:
        NAME: "rabbitmq1"
    networks:
      app_net:
        ipv4_address: 10.123.123.253

  primarydb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SistemiDistribuiti2017
      MYSQL_USER: root
      MYSQL_PASSWORD: SistemiDistribuiti2017
      MYSQL_DATABASE: sistemidistribuiti
    networks:
      app_net:
        ipv4_address: 10.123.123.200

  replica1:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: SistemiDistribuiti2017
      MYSQL_USER: root
      MYSQL_PASSWORD: SistemiDistribuiti2017
      MYSQL_DATABASE: sistemidistribuiti
    networks:
      app_net:
        ipv4_address: 10.123.123.201

  replica2:
    image: mysql
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: SistemiDistribuiti2017
      MYSQL_USER: root
      MYSQL_PASSWORD: SistemiDistribuiti2017
      MYSQL_DATABASE: sistemidistribuiti
    networks:
      app_net:
        ipv4_address: 10.123.123.202

  replica3:
    image: mysql
    ports:
      - "3309:3309"
    environment:
      MYSQL_ROOT_PASSWORD: SistemiDistribuiti2017
      MYSQL_USER: root
      MYSQL_PASSWORD: SistemiDistribuiti2017
      MYSQL_DATABASE: sistemidistribuiti
    networks:
      app_net:
        ipv4_address: 10.123.123.203

  replica4:
    image: mysql
    ports:
      - "3310:3310"
    environment:
      MYSQL_ROOT_PASSWORD: SistemiDistribuiti2017
      MYSQL_USER: root
      MYSQL_PASSWORD: SistemiDistribuiti2017
      MYSQL_DATABASE: sistemidistribuiti
    networks:
      app_net:
        ipv4_address: 10.123.123.204

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.123.123.0/24       
